name: CI

jobs:
      build-and-push:
            runs-on: ubuntu-latest   #GitHub Runner
            steps: 
                   -uses: actions/checkout@v4 #clone the code

                   -uses: docker/setup-buildx-action@v4
